# Based on Node 16 Alpine image
FROM node:18-alpine

# Install system requirements
RUN apk add --no-cache alpine-sdk bash

# Set the default directory where CMD will execute
WORKDIR /app

# Expose our application ports
EXPOSE 8000

# Set the default command to execute when creating a new container
CMD /bin/bash -c "yarn && yarn dev"

